### ISSUE TITLE
Issue not seeing linting appear

### ISSUE THREAD

**Issue by d-farrell** [Shopify/theme-check-vscode#110]
Hi I am having an issue not seeing the linting messaging that a colleague of mine is able to see. Is there something I need to check I have installed?

I am expecting to see this type of lint error but I dont.
<img width="1331" alt="Screenshot 2023-01-13 at 11 55 26" src="https://user-images.githubusercontent.com/96251310/212314917-ce027540-68dd-4d5f-9e1a-8114d62b9dd1.png">

Any help or suggestions on anything i've missed or can check?

**Comment by charlespwd** [comment]
A few questions:
- Do you have either theme-check or shopify CLI installed? 
- List of VS Code plugins related to Liquid installed?
- Windows or macOS or Linux?


Observation:
- The first error doesn't seem like it would be coming from us. I don't recall having "was not properly terminated with" errors. Could be wrong.

**Comment by d-farrell** [comment]
@charlespwd I am using macOS and I just have Shopify Liquid 1.9.4 installed and Shopify CLI installed at the moment (related to this)

When I run `shopify theme check` I see a bunch of suggested changes and then this error. But nothing within the file I look at in VScode highlights to any potential issues that should be fixed.

```
585 files inspected, 355 offenses detected, 255 offenses auto-correctable
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Theme check failed with error:
┃ /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/cli.rb:197:in `check': ThemeCheck::Cli::Abort
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/theme-check-1.14.0/lib/theme_check/cli.rb:123:in `run!'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/project_types/theme/commands/check.rb:27:in `call'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/command.rb:27:in `call'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/core/executor.rb:15:in `call'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/core/entry_point.rb:17:in `block in call'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/core/monorail.rb:26:in `log'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/lib/shopify_cli/core/entry_point.rb:16:in `call'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/bin/shopify:49:in `block in <top (required)>'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/shopify-cli-2.34.0/bin/shopify:59:in `<top (required)>'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/bin/shopify:25:in `load'
┃       from /Users/danielfarrell/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/bin/shopify:25:in `<top (required)>'
┃       from /usr/local/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
┃       from /usr/local/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
┃       from /usr/local/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
┃       from /usr/local/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli.rb:491:in `exec'
┃       from /usr/local/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
┃       from /usr/local/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
┃       from /usr/local/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
┃       from /usr/local/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
┃       from /usr/local/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
┃       from /usr/local/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
┃       from /usr/local/Cellar/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/exe/bundle:45:in `block in <top (required)>'
┃       from /usr/local/Cellar/ruby/3.2.0/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
┃       from /usr/local/Cellar/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/exe/bundle:33:in `<top (required)>'
┃       from /usr/local/opt/ruby/bin/bundle:25:in `load'
┃       from /usr/local/opt/ruby/bin/bundle:25:in `<main>'

**Comment by d-farrell** [comment]
I tried `brew install shopify/shopify/theme-check` but still getting the same error as above when I run anything from the commands such as `shopify theme check --auto-correct`

**Comment by charlespwd** [comment]
Right the command line should be `theme-check` not `shopify theme check`

**Comment by d-farrell** [comment]
Ah I see. Thank you! :)
